### ISSUE TITLE
Bug Eloqua Form Contact us null - LA export market countries

### ISSUE THREAD

**Issue by manuel-vara** [hlxsites/vg-macktrucks-com-ni#14]
<img width="1562" alt="image" src="https://github.com/hlxsites/vg-macktrucks-com-ni/assets/116451851/8bc93fbd-ec37-46d3-b276-9d9d049b7472">

**Comment by BeckyMedlin** [comment]
@DanielaPedrochevd What is the status of this ticket? Thanks!

**Comment by jonatan-lledo-netcentric** [comment]
status updated to _PR in review_ (or _Ready for PR_) @manuel-vara @BeckyMedlin
